In [1]:
from sklearn import datasets
from sklearn.feature_selection import VarianceThreshold

iris = datasets.load_iris()

features = iris.data
target = iris.target

thresholder = VarianceThreshold(threshold=.5)

features_high_variance = thresholder.fit_transform(features)

features_high_variance[0]


array([5.1, 1.4, 0.2])

In [2]:
from sklearn.feature_selection import VarianceThreshold

features = ([0, 1, 0],[0,1,1],[0,1,0],[0,1,1],[1,0,0])
thresholder = VarianceThreshold(threshold=(.75 * (1 - .75)))
thresholder.fit_transform(features)

array([[0],
       [1],
       [0],
       [1],
       [0]])

In [3]:
import pandas as pd
import numpy as np

features = np.array([[1,1,1],
                    [2,2,0],
                    [3,3,1],
                    [4,4,0],
                    [5,5,1],
                    [6,6,0],
                    [7,7,1],
                    [8,7,0],
                    [9,7,1]])

dataframe = pd.DataFrame(features)

corr_matrix = dataframe.corr().abs()

upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape),k=1).astype(np.bool))

to_drop = [column for column in upper.columns if any(upper[column] > 0.95)]

dataframe.drop(dataframe.columns[to_drop], axis=1)

0  2
0  1  1
1  2  0
2  3  1
3  4  0
4  5  1
5  6  0
6  7  1
7  8  0
8  9  1

In [4]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2, f_classif

iris = load_iris()
features = iris.data
target = iris.target

features = features.astype(int)

chi2_selector = SelectKBest(chi2, k = 2)
features_kbest = chi2_selector.fit_transform(features, target)

In [5]:
import warnings
from sklearn.datasets import make_regression
from sklearn.feature_selection import RFECV
from sklearn import datasets, linear_model

warnings.filterwarnings(action = "ignore", module = "scipy", message = "internal gelsd")

features, target = make_regression(n_samples = 10000,
                                  n_features = 100,
                                  n_informative = 2,
                                  random_state = 1)

ols = linear_model.LinearRegression()

rfecv = RFECV(estimator=ols, step=1, scoring="neg_mean_squared_error")
rfecv.fit(features,target)
rfecv.transform(features)

C:\Users\fujii\Anaconda3\envs\tesorflow-gpu\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


array([[ 0.00850799, -0.90516493,  0.7031277 ],
       [-1.07500204,  0.24492446,  2.56148527],
       [ 1.37940721, -1.00386608, -1.77039484],
       ...,
       [-0.80331656,  1.41968814, -1.60648007],
       [ 0.39508844,  0.58606125, -1.34564911],
       [-0.55383035, -0.98351148,  0.82880112]])

In [6]:
rfecv.n_features_

3

In [7]:
rfecv.support_

array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])

In [8]:
rfecv.ranking_

array([27, 33, 93, 95, 59,  1, 38, 80,  3, 62, 69, 24, 51, 81, 32, 17, 57,
       36, 53, 52, 77, 37, 92, 86, 47, 78, 44,  1, 25, 60, 54, 42, 22, 15,
        5, 50, 98, 10, 21,  1, 73, 67, 31, 96, 89, 13, 61, 16, 40, 97, 90,
        6, 46, 45, 23, 39, 29, 26, 75, 12, 76, 49,  7, 35, 70, 74, 58, 64,
       43, 66, 94, 79,  9,  4, 85, 83, 71, 41, 14, 65, 91, 30,  8,  2, 72,
       19, 20, 82, 48, 11, 55, 28, 18, 68, 84, 56, 63, 34, 88, 87])